version: '3'

services:
  web:
    build: .
    image: artege_app:latest
    container_name: artege_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_NAME=artege_db
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=password
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: artege_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: