apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artege-app
spec:
  destination:
    name: ''
    namespace: artege
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/
    repoURL: 'https://github.com/stefanikulebanova/DevOps-Project'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - Validate=false
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true