apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-project-config
  namespace: artege
data:
  POSTGRES_HOST: kiii-project-postgres-service.artege
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: kiii-project-secret
  namespace: artege
type: Opaque
data:
  password: cG9zdGdyZXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-project-deployment
  namespace: artege
spec:
  replicas: 2
  selector:
    matchLabels:
      app: artege_app
  template:
    metadata:
      labels:
        app: artege_app
    spec:
      containers:
        - name: kiii-project
          image: stefani01/kiii-project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: kiii-project-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kiii-project-secret
                  key: password
          command: ["python","./manage.py", "runserver", "0.0.0.0:80"]