apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: artege
  namespace: ns2
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`artege.net`)
      kind: Rule
      services:
        - name: artege
          namespace: artege
          port: 80