apiVersion: v1
kind: Service
metadata:
  name: service-1
  namespace: kube-system
spec:
  type: ExternalName
  externalName: service-1.artege.svc.cluster.local
  ports:
    - name: http
      port: 8080
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: kiii-project-ingress
  namespace: artege
spec:
  rules:
    - host: latest.example.com
      http:
        paths:
          - backend:
              serviceName: service-1
              servicePort: 80
              path: /