apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiii-project-ingress
  namespace: artege
  className: nginx
spec:
 rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kiii-project-service
            port:
              number: 80