apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-project-postgres-config
  namespace: artege
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: kiii-project-postgres-secret
  namespace: artege
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kiii-project-postgres-pvc
  namespace: artege
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kiii-project-postgres
  namespace: artege
spec:
  serviceName: kiii-project-postgres-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        namespace: artege
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: kiii-project-postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kiii-project-postgres-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - name: kiii-project-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: kiii-project-postgres-data
          persistentVolumeClaim:
            claimName: kiii-project-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-project-postgres-service
  namespace: artege
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres